### ISSUE TITLE
Skládání PC

### ISSUE THREAD

**Issue by elPytel** [elPytel/PDO-Psani_technicke_dokumentace#3]
## TODO:
- [x] Doplnit obrázky (uvítací obrazovka Win)
- [ ] Přidejte malou sekci o vybalení z krabice
- [x] Myslím že místo odrážek máme použít číslované seznamy (vedou uživatele krok za krokem)

### Dotaz zmateného uživatele co vidí svůj první stolní počítač
- [x] Kde najdeme na počítači základní desku a jak do ní něco připojíme?
- [x] Co je to HDMI kabel a jak vypadá?

**Comment by JanPodavka** [comment]
done, vybalení z krabice už je moc low level
